
#controllers/nginx-deploy.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-deployment
  labels:
    app: employee_app-cluster
    owner: onkar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: employee-app
  template:
    metadata:
      labels:
        app: employee-app
    spec:
      containers:
        - name: employeeapp-container
          image: devopsedu/employee
          ports:
          - containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-app-svc
  labels:
    app: nodejs-app-svc
    owner: onkar
spec:
  selector:
    app: employee-app
  type: NodePort
  ports:
  - nodePort: 31001
    port: 8888
    targetPort: 8888
