#
#controllers/nginx-deploy.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  labels:
    app: mongodb_app-cluster
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb-app
  template:
    metadata:
      labels:
        app: mongodb-app
    spec:
      containers:
        - name: mongo-container
          image: mongo
          ports:
          - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-app-svc
  labels:
    app: mongodb_app-svc
spec:
  selector:
    app: mongodb_app-cluster
  type: NodePort
  ports:
  - nodePort: 31000
    port: 27017
    targetPort: 27017
